import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import dynamic from 'next/dynamic'
import { Box, CssBaseline } from "@mui/material";
import AuthProvider from "@/context/AuthProvider";
import ThemeContextProvider from "./theme/ThemeContextProvider";

const _NavBar = dynamic(() => import('./components/navbar/NavBar'), { ssr: false })
const _Footer = dynamic(() => import('./components/footer/Footer'), { ssr: false })

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <ThemeContextProvider>
          <CssBaseline />
          <body>
            <_NavBar />
            <Box>
              {children}
            </Box>
            <_Footer />
          </body>
        </ThemeContextProvider>
      </AuthProvider>
    </html>
  );
}
